# https://taskfile.dev

version: "3"

vars: {}

tasks:
  list:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - task --list-all
    silent: true

  remove_system_files:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - find . -name ".DS_Store" -type f -delete -print
      - find . -name "core" -type f -delete -print
      - find . -name "node_modules" -type d -print -exec rm -rf {} +
    silent: true

  init:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      # remove system files
      - task remove_system_files
      # キャッシュクリア (skillsの読み込み時にcacheが悪さすることが多い)
      - rm -rf ./.claude-home-cache/plugins/cache/*
      # python
      - task uv_sync
    silent: false

  fmt:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - treefmt
    silent: false

  uv_sync:
    dir: "{{ .TASKFILE_DIR }}/python"
    cmds:
      - uv sync --link-mode=copy --frozen
    silent: true

  serve:
    dir: "{{ .TASKFILE_DIR }}/node/"
    cmds:
      - npm run build
      - docker run -it --rm -v ${LOCAL_WORKSPACE_FOLDER}/node/dist/:/usr/share/nginx/html/ -p 8000:80 nginx
    silent: true
