[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "duckdb>=1.3.0",
    "pandas>=2.3.0",
    "requests>=2.32.3",
    "urlextract>=1.9.0",
]
