name: Deploy GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# 参考
# * https://zenn.dev/kanakanho/articles/3a8b313e698b7f
# * https://github.com/actions/setup-node
# * https://github.com/actions/setup-python 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: Setup pip
        run:  |
          cd python 
          pip install -r requirements.txt
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Setup npm
        run: |
          cd node
          npm install
      - name: Build DuckDB Persistent Database
        run: |
          cd python
          python apps/trasform_rfc_index_to_json.py --file ./rfc-index.json
          python apps/extract_rfc_referencing_urls_from_rfc_txts.py --file ./rfc-referencing-urls.json
          python apps/create_duckdb_persistent_db.py --dbfile ./rfc.duckdb --rfc-index ./rfc-index.json --rfc-referencing-urls ./rfc-referencing-urls.json
      - name: Copy DuckDB Persistent Database
        run:  cp python/rfc.duckdb node/src/rfc.duckdb
      - name: Build with Vite
        run: |
          cd node
          npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'node/dist/'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
